export interface MedicationRecord {
    id?: string // ID only set when retrieved from db
    name: string;
    dosage: string;
    form: MedicationRecordForm;
    amount?: number;
    missed?: boolean;
    scheduledTime: Date;
}

// FIXME: This was generated by the copilot, so I'm not sure if it's correct
export enum MedicationRecordForm {
    TABLET = 'Tablet',
    CAPSULE = 'Capsule',
    SYRUP = 'Syrup',
    INJECTION = 'Injection',
    DROPS = 'Drops',
    INHALER = 'Inhaler',
    CREAM = 'Cream',
    OINTMENT = 'Ointment',
    LOTION = 'Lotion',
    SUPPOSITORY = 'Suppository',
    POWDER = 'Powder',
    GEL = 'Gel',
    SPRAY = 'Spray',
    PATCH = 'Patch',
    IMPLANT = 'Implant',
    MOUTHWASH = 'Mouthwash',
    SOLUTION = 'Solution',
    SUSPENSION = 'Suspension',
    EMULSION = 'Emulsion',
    AEROSOL = 'Aerosol',
    MIST = 'Mist',
    FOAM = 'Foam',
    OIL = 'Oil',
    GARGLE = 'Gargle',
    PASTE = 'Paste',
    JELLY = 'Jelly',
    ENEMA = 'Enema',
    PESSARY = 'Pessary',
    DUSTING = 'Dusting',
    DRESSING = 'Dressing',
    WASH = 'Wash',
    SHAMPOO = 'Shampoo',
    LINIMENT = 'Liniment',
    SOAP = 'Soap',
    CLEANSER = 'Cleanser',
    SHOWER = 'Shower',
    BATH = 'Bath',
    SPRINKLE = 'Sprinkle',
    SOAK = 'Soak',
    DROPPER = 'Dropper',
    SWAB = 'Swab',
    TINCTURE = 'Tincture',
}
